name: Prettier and Style Check

on:
  push:
    branches:
      - main

jobs:
  prettier-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier:check -- --ignore-path ./backend/.gitignore

      - name: Run Nest.js lint
        run: npm run lint -- --ignore-path ./backend/.gitignore
